import type { PrismaClient } from "@/generated/prisma/client";
import { ExternalResourceType, ParticipantRole, RaceMomentStatus, RaceMomentType, RaceStatus, SessionType, SourceKind, SourceProvider } from "@/generated/prisma/enums";
import { canonicalRaceFixtures } from "@/lib/f1/fixtures/canonical-races";

const upperSnake = (value: string) => value.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase();

export async function seedCanonicalFixtures(database: PrismaClient) {
  const fixture = canonicalRaceFixtures;
  await database.$transaction(async (tx) => {
    for (const source of fixture.sources) {
      await tx.source.upsert({ where: { id: source.id }, update: { provider: SourceProvider[upperSnake(source.provider) as keyof typeof SourceProvider], kind: SourceKind[upperSnake(source.kind) as keyof typeof SourceKind], title: source.title, url: source.url, publishedAt: source.publishedAt ? new Date(source.publishedAt) : null, retrievedAt: new Date(source.retrievedAt) }, create: { id: source.id, provider: SourceProvider[upperSnake(source.provider) as keyof typeof SourceProvider], kind: SourceKind[upperSnake(source.kind) as keyof typeof SourceKind], title: source.title, url: source.url, publishedAt: source.publishedAt ? new Date(source.publishedAt) : undefined, retrievedAt: new Date(source.retrievedAt) } });
    }
    for (const season of fixture.seasons) await tx.season.upsert({ where: { id: season.id }, update: { year: season.year }, create: { id: season.id, year: season.year } });
    for (const circuit of fixture.circuits) await tx.circuit.upsert({ where: { id: circuit.id }, update: { slug: circuit.slug, name: circuit.name, locality: circuit.locality, country: circuit.country, countryCode: circuit.countryCode }, create: { id: circuit.id, slug: circuit.slug, name: circuit.name, locality: circuit.locality, country: circuit.country, countryCode: circuit.countryCode } });
    for (const grandPrix of fixture.grandsPrix) await tx.grandPrix.upsert({ where: { id: grandPrix.id }, update: { seasonId: grandPrix.seasonId, circuitId: grandPrix.circuitId, round: grandPrix.round, officialName: grandPrix.officialName, shortName: grandPrix.shortName, startDate: new Date(`${grandPrix.startDate}T00:00:00Z`), endDate: new Date(`${grandPrix.endDate}T00:00:00Z`) }, create: { id: grandPrix.id, seasonId: grandPrix.seasonId, circuitId: grandPrix.circuitId, round: grandPrix.round, officialName: grandPrix.officialName, shortName: grandPrix.shortName, startDate: new Date(`${grandPrix.startDate}T00:00:00Z`), endDate: new Date(`${grandPrix.endDate}T00:00:00Z`) } });
    for (const session of fixture.sessions) await tx.session.upsert({ where: { id: session.id }, update: { grandPrixId: session.grandPrixId, type: SessionType[upperSnake(session.type) as keyof typeof SessionType], name: session.name, startsAt: new Date(session.startsAt), endsAt: session.endsAt ? new Date(session.endsAt) : null }, create: { id: session.id, grandPrixId: session.grandPrixId, type: SessionType[upperSnake(session.type) as keyof typeof SessionType], name: session.name, startsAt: new Date(session.startsAt), endsAt: session.endsAt ? new Date(session.endsAt) : undefined } });
    for (const race of fixture.races) await tx.race.upsert({ where: { id: race.id }, update: { grandPrixId: race.grandPrixId, sessionId: race.sessionId, status: RaceStatus[upperSnake(race.status) as keyof typeof RaceStatus], scheduledLaps: race.scheduledLaps, actualLaps: race.actualLaps, startedAt: race.startedAt ? new Date(race.startedAt) : null, endedAt: race.endedAt ? new Date(race.endedAt) : null }, create: { id: race.id, grandPrixId: race.grandPrixId, sessionId: race.sessionId, status: RaceStatus[upperSnake(race.status) as keyof typeof RaceStatus], scheduledLaps: race.scheduledLaps, actualLaps: race.actualLaps, startedAt: race.startedAt ? new Date(race.startedAt) : undefined, endedAt: race.endedAt ? new Date(race.endedAt) : undefined } });
    for (const driver of fixture.drivers) await tx.driver.upsert({ where: { id: driver.id }, update: { slug: driver.slug, givenName: driver.givenName, familyName: driver.familyName, code: driver.code, permanentNumber: driver.permanentNumber, nationality: driver.nationality }, create: { id: driver.id, slug: driver.slug, givenName: driver.givenName, familyName: driver.familyName, code: driver.code, permanentNumber: driver.permanentNumber, nationality: driver.nationality } });
    for (const team of fixture.teams) await tx.team.upsert({ where: { id: team.id }, update: { slug: team.slug, canonicalName: team.canonicalName }, create: { id: team.id, slug: team.slug, canonicalName: team.canonicalName } });
    for (const identity of fixture.teamSeasonIdentities) await tx.teamSeasonIdentity.upsert({ where: { id: identity.id }, update: { teamId: identity.teamId, seasonId: identity.seasonId, displayName: identity.displayName, constructorName: identity.constructorName, nationality: identity.nationality, validFrom: new Date(`${identity.validFrom}T00:00:00Z`), validTo: identity.validTo ? new Date(`${identity.validTo}T00:00:00Z`) : null }, create: { id: identity.id, teamId: identity.teamId, seasonId: identity.seasonId, displayName: identity.displayName, constructorName: identity.constructorName, nationality: identity.nationality, validFrom: new Date(`${identity.validFrom}T00:00:00Z`), validTo: identity.validTo ? new Date(`${identity.validTo}T00:00:00Z`) : undefined } });
    for (const membership of fixture.driverTeamMemberships) await tx.driverTeamMembership.upsert({ where: { id: membership.id }, update: { driverId: membership.driverId, teamId: membership.teamId, seasonId: membership.seasonId, carNumber: membership.carNumber, validFrom: new Date(`${membership.validFrom}T00:00:00Z`), validTo: membership.validTo ? new Date(`${membership.validTo}T00:00:00Z`) : null }, create: { id: membership.id, driverId: membership.driverId, teamId: membership.teamId, seasonId: membership.seasonId, carNumber: membership.carNumber, validFrom: new Date(`${membership.validFrom}T00:00:00Z`), validTo: membership.validTo ? new Date(`${membership.validTo}T00:00:00Z`) : undefined } });
    for (const moment of fixture.moments) {
      await tx.raceMoment.upsert({ where: { id: moment.id }, update: { raceId: moment.raceId, sessionId: moment.sessionId, slug: moment.slug, type: RaceMomentType[upperSnake(moment.type) as keyof typeof RaceMomentType], status: RaceMomentStatus[upperSnake(moment.status) as keyof typeof RaceMomentStatus], title: moment.title, summary: moment.summary, lapNumber: moment.lapNumber, occurredAt: moment.occurredAt ? new Date(moment.occurredAt) : null, sequence: moment.sequence, importance: moment.importance }, create: { id: moment.id, raceId: moment.raceId, sessionId: moment.sessionId, slug: moment.slug, type: RaceMomentType[upperSnake(moment.type) as keyof typeof RaceMomentType], status: RaceMomentStatus[upperSnake(moment.status) as keyof typeof RaceMomentStatus], title: moment.title, summary: moment.summary, lapNumber: moment.lapNumber, occurredAt: moment.occurredAt ? new Date(moment.occurredAt) : undefined, sequence: moment.sequence, importance: moment.importance } });
      await tx.raceMomentDriver.deleteMany({ where: { raceMomentId: moment.id } });
      await tx.raceMomentDriver.createMany({ data: moment.drivers.map((participant) => ({ raceMomentId: moment.id, driverId: participant.entityId, role: ParticipantRole[upperSnake(participant.role) as keyof typeof ParticipantRole] })) });
      await tx.raceMomentTeam.deleteMany({ where: { raceMomentId: moment.id } });
      await tx.raceMomentTeam.createMany({ data: moment.teams.map((participant) => ({ raceMomentId: moment.id, teamId: participant.entityId, role: ParticipantRole[upperSnake(participant.role) as keyof typeof ParticipantRole] })) });
      await tx.raceMomentSource.deleteMany({ where: { raceMomentId: moment.id } });
      await tx.raceMomentSource.createMany({ data: moment.sourceIds.map((sourceId) => ({ raceMomentId: moment.id, sourceId })) });
    }
    for (const reference of fixture.externalReferences) {
      const entityKey = `${reference.resourceType}Id` as const;
      const relation = { [entityKey]: reference.entityId };
      await tx.externalDataReference.upsert({ where: { id: reference.id }, update: { provider: SourceProvider[upperSnake(reference.provider) as keyof typeof SourceProvider], resourceType: ExternalResourceType[upperSnake(reference.resourceType) as keyof typeof ExternalResourceType], externalId: reference.externalId, sourceId: reference.sourceId, sourceUrl: reference.sourceUrl, fetchedAt: new Date(reference.fetchedAt), sourceTimestamp: reference.sourceTimestamp ? new Date(reference.sourceTimestamp) : null, ...relation }, create: { id: reference.id, provider: SourceProvider[upperSnake(reference.provider) as keyof typeof SourceProvider], resourceType: ExternalResourceType[upperSnake(reference.resourceType) as keyof typeof ExternalResourceType], externalId: reference.externalId, sourceId: reference.sourceId, sourceUrl: reference.sourceUrl, fetchedAt: new Date(reference.fetchedAt), sourceTimestamp: reference.sourceTimestamp ? new Date(reference.sourceTimestamp) : undefined, ...relation } });
    }
  });
  return { races: fixture.races.length, moments: fixture.moments.length, sources: fixture.sources.length };
}
